name = "genofit"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# This configuration is for Cloudflare Pages
# The actual deployment will be handled by the pages deploy command