name = "genofit"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Manual worker configuration
main = "_worker.js"

# Static assets configuration
[assets]
directory = "out"
binding = "ASSETS"